@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.powerscale.loot.condition;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;