@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.powerscale.loot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;