@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.powerscale.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;