@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.powerscale.compat.jei;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;